@startuml Sistema
title Modelo Dominio - Sistema de Gestión de Biblioteca

class Usuario

class Contacto

class SolicitudCompartir

Usuario "1" -- "" Contacto : gestiona
Usuario "1" --> "" SolicitudCompartir : envia
Usuario "1" --> "*" SolicitudCompartir : recibe

@enduml