@startuml Sistema de Gestor de Contanctos
title Modelo de Dominio - Sistema Gestor de Contactos

class Usuario 
class Contacto
class SolicitudCompartir 
class SistemaUsuarios 

' Usuario tiene muchos contactos
Usuario "1" -- "1..*" Contacto : posee >

' Solicitudes enviadas por un usuario
Usuario "1" -- "0..*" SolicitudCompartir : envia >

' Solicitudes recibidas por un usuario
Usuario "1" -- "0..*" SolicitudCompartir : recibe <

SolicitudCompartir "1" --> "1" Usuario : solicitante
SolicitudCompartir "1" --> "1" Usuario : destinatario

' SistemaUsuarios administra a varios usuarios
SistemaUsuarios "1" -- "0..*" Usuario : contiene >

@enduml
