@startuml Dominio

entity Usuario

entity Contacto

entity SolicitudCompartir

' Relaciones
Usuario "1" -- "*" Contacto : gestiona

Usuario "1" --> "*" SolicitudCompartir : envia
Usuario "1" --> "*" SolicitudCompartir : recibe
@enduml